import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Wallpaper from '../components/Wallpaper'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { faCrutch } from '@fortawesome/free-solid-svg-icons'
import { faCheck } from '@fortawesome/free-solid-svg-icons'
import { faPhone } from '@fortawesome/free-solid-svg-icons'

export default function jobs() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>

                <Wallpaper srcString={"/../public/assets/jobs-wallpaper.jpg"} />

                <div id="job-offer-container" className='w-auto px-6 lg:px-[20%] py-12 flex justify-center flex-col'>
                    <h2 className='text-4xl text-center text-[color:var(--ls-blue)] font-extrabold'> Auf der Suche nach einem <br />  <strong>spannenden</strong>  Job im Herzen der Uckermark?</h2>
                    <br />
                    <p > Wenn Sie zuverlässig sind und gut gelaunt in einem dynamischen Team arbeiten möchten, dann melden Sie sich bei uns telefonisch. Für Auskünfte steht Ihnen Frau Löser ( <FontAwesomeIcon icon={faPhone} /> 039852-18836)  gerne zur Verfügung.</p>
                    <br />
                    <div className="job-details-container w-full lg:w-auto block py-5 px-5 lg:px-12 my-5 mx-0 lg:mx-[10%] rounded-2xl border-8 border-[color:var(--ls-yellow)]">
                        <h3 className='text-2xl lg:text-3xl w-auto font-extrabold text-[color:var(--ls-blue)] text-center lg:text-left'> Ihre Aufgaben in der Pflege bei uns:</h3>
                        <br />
                        <ul className='text-md lg:text-lg'>
                            <li><FontAwesomeIcon icon={faCrutch} className='fa-flip-horizontal' /> Grund- und Behandlungspflege</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCrutch} className='fa-flip-horizontal' /> Dokumentation der Pflegearbeit</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCrutch} className='fa-flip-horizontal' /> Administrative Tätigkeiten</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCrutch} className='fa-flip-horizontal' /> Umsetzen unseres Pflegekonzepts</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCrutch} className='fa-flip-horizontal' /> Einbringen in das Team mit kreativen und innovativen Ideen</li>
                        </ul>
                    </div>

                    <div className="job-details-container job-details-container w-full lg:w-auto block py-5 px-5 lg:px-12 my-5 mx-0 lg:mx-[10%] rounded-2xl border-8 border-[color:var(--ls-yellow)]">
                        <h3 className='text-2xl lg:text-3xl w-auto font-extrabold text-[color:var(--ls-blue)] text-center lg:text-left'> Das erwartet Sie:</h3>
                        <br />
                        <ul className=' text-md lg:text-lg'>
                            <li><FontAwesomeIcon icon={faCheck} /> Grund- und Behandlungspflege</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCheck} /> Dokumentation der Pflegearbeit</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCheck} /> Administrative Tätigkeiten</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCheck} /> Umsetzen unseres Pflegekonzepts</li>
                            <br />
                            <li><FontAwesomeIcon icon={faCheck} /> Einbringen in das Team mit kreativen und innovativen Ideen</li>
                        </ul>
                    </div>


                </div>

            </main>
            <Footer />
        </>
    )
}
