import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Wallpaper from '../components/Wallpaper'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { faCrutch } from '@fortawesome/free-solid-svg-icons'
import { faCheck } from '@fortawesome/free-solid-svg-icons'
import { faPhone } from '@fortawesome/free-solid-svg-icons'
import imageUrlBuilder from '@sanity/image-url'


import client from '../client'

export default function jobs(data) {

    function urlFor(source) {
        return imageUrlBuilder(client).image(source)
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>

            <Wallpaper srcString={urlFor(data.data.image.asset._ref).url()} />

                <div id="job-offer-container" className='w-auto px-6 lg:px-[20%] py-12 flex justify-center flex-col'>
                    <h2 className='text-4xl text-center text-[color:var(--ls-blue)] font-extrabold'> {data.data.pageHeading} </h2>
                    <br />
                    <p > {data.data.pageSubheading} </p>
                    <br />
                    <div className="job-details-container w-full lg:w-auto block py-5 px-5 lg:px-12 my-5 mx-0 lg:mx-[10%] rounded-2xl border-8 border-[color:var(--ls-yellow)]">
                        <h3 className='text-2xl lg:text-3xl w-auto font-extrabold text-[color:var(--ls-blue)] text-center lg:text-left'>{data.data.boxTopHeading}</h3>
                        <br />
                        <ul className='text-md lg:text-lg'>
                            {
                                data.data.boxTopArray && data.data.boxTopArray.map(e => (
                                    <>
                                        <li><FontAwesomeIcon icon={faCrutch} className='fa-flip-horizontal mr-2' />{e}</li>
                                        <br />
                                    </>
                                ))
                            }
                        </ul>
                    </div>

                    <div className="job-details-container job-details-container w-full lg:w-auto block py-5 px-5 lg:px-12 my-5 mx-0 lg:mx-[10%] rounded-2xl border-8 border-[color:var(--ls-yellow)]">
                        <h3 className='text-2xl lg:text-3xl w-auto font-extrabold text-[color:var(--ls-blue)] text-center lg:text-left'>{data.data.boxBottomHeading}</h3>
                        <br />
                        <ul className=' text-md lg:text-lg'>
                            {
                                data.data.boxBottomArray && data.data.boxBottomArray.map(e => (
                                    <>
                                        <li><FontAwesomeIcon icon={faCheck} className='mr-2' />{e}</li>
                                        <br />
                                    </>
                                ))
                            }
                        </ul>
                    </div>
                </div>

            </main>
            <Footer />
        </>
    )
}

export async function getStaticProps() {
    const data = await client.fetch(`*[_type=='jobsPage'][0]`);

    return {
        props: {
            data
        }
    };
}