import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Wallpaper from '../components/Wallpaper'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import '@fortawesome/fontawesome-svg-core/styles.css'
import DoubleFacedCard from '../components/DoubleFacedCard'
import { faHospital } from '@fortawesome/free-solid-svg-icons'
import { faHospitalUser } from '@fortawesome/free-solid-svg-icons'
import { faPersonCane } from '@fortawesome/free-solid-svg-icons'
import { faPeopleRoof } from '@fortawesome/free-solid-svg-icons'
import { faPersonShelter } from '@fortawesome/free-solid-svg-icons'

const Krankenkasse = {
    title: "Leistungen der Krankenkassen",
    text: "Häusliche Krankenpflege ist eine Leistung der gesetzlichen Krankenkasse und wird dann durchgeführt, wenn die Versorgung vom Patienten oder dessen Angehörigen nicht selber durchgeführt werden kann.",
    hoverText: {
        type: "array",
        content: [
            "Medikamentenvergabe und Hilfe beim Einnehmen",
            "Gabe von Injektonen und Infusionen",
            "Wechsel von Verbänden",
            "Katheter-, Stoma- und Portversorgung",
            "+ viele weitere Leistungen"
        ]
    }
}
const Pflegekasse = {
    title: "Leistungen der Pflegekasse",
    text: "Wir unterstützen Sie mit unserer ambulanten Seniorenbetreuung bei behördlichen und medizinischen Angelegenheiten, begleiten Sie zu Behörden und Kassen und holen für Sie Rezepte ab.",
    hoverText: {
        type: "array",
        content: [
            "Realisierung der entsprechenden Leistungen der Pflegegrade 1-5",
            "Sach- und Kombinationsleistungen",
            "Tagespflege und Wohngemeinschaften",
            "Körperpflege: Hilfe und Durchführung",
            "Abstimmung der benötigten Pflegedienstleistungen nach individuellen Bedürfnissen und Lebenslage"
        ]
    }
}
const Tagespflege = {
    title: "Tagespflege",
    text: "Wir haben eine Tagespflege in [Ort].",
    hoverText: {
        type: "array",
        content: [
            "a",
            "a",
            "a",
            "a"
        ]
    }
}
const Seniorengemeinschaft = {
    title: "Senioren-Wohngemeinschaft",
    text: "Wir besitzen eine Senioren-Wohngemeinschaft mit 24h vor-Ort-Betreuung in Gollmitz.",
    hoverText: {
        type: "array",
        content: [
            "a",
            "a",
            "a",
            "a"
        ]
    }
}

export default function leistungen() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>
                <Wallpaper srcString={"/../public/assets/jobs-wallpaper.jpg"} />
                <div className='max-w-6xl mx-auto flex flex-row flex-wrap justify-evenly'>
                    <DoubleFacedCard title={Krankenkasse.title} text={Krankenkasse.text} icon={faHospitalUser} hoverText={Krankenkasse.hoverText} />
                    <DoubleFacedCard title={Pflegekasse.title} text={Krankenkasse.text} icon={faPersonCane} hoverText={Pflegekasse.hoverText} />
                    <DoubleFacedCard title={Tagespflege.title} text={Tagespflege.text} icon={faPeopleRoof} hoverText={Tagespflege.hoverText} />
                    <DoubleFacedCard title={Seniorengemeinschaft.title} text={Seniorengemeinschaft.text} icon={faPersonShelter} hoverText={Seniorengemeinschaft.hoverText} />
                </div>
            </main>
            <Footer />
        </>
    )
}
