import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Wallpaper from '../components/Wallpaper'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import '@fortawesome/fontawesome-svg-core/styles.css'
import DoubleFacedCard from '../components/DoubleFacedCard'
import { faHospital } from '@fortawesome/free-solid-svg-icons'
import { faHospitalUser } from '@fortawesome/free-solid-svg-icons'
import { faPersonCane } from '@fortawesome/free-solid-svg-icons'
import { faPeopleRoof } from '@fortawesome/free-solid-svg-icons'
import { faPersonShelter } from '@fortawesome/free-solid-svg-icons'

export default function leistungen() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>
                <Wallpaper srcString={urlFor(data.data.image.asset._ref).url()} />
                <div className='max-w-6xl mx-auto flex flex-row flex-wrap justify-evenly'>
                    <DoubleFacedCard title={Krankenkasse.title} text={Krankenkasse.text} icon={faHospitalUser} hoverText={Krankenkasse.hoverText} />
                    <DoubleFacedCard title={Pflegekasse.title} text={Krankenkasse.text} icon={faPersonCane} hoverText={Pflegekasse.hoverText} />
                    <DoubleFacedCard title={Tagespflege.title} text={Tagespflege.text} icon={faPeopleRoof} hoverText={Tagespflege.hoverText} />
                    <DoubleFacedCard title={Seniorengemeinschaft.title} text={Seniorengemeinschaft.text} icon={faPersonShelter} hoverText={Seniorengemeinschaft.hoverText} />
                </div>
            </main>
            <Footer />
        </>
    )
}
