import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Wallpaper from '../components/Wallpaper'
import SingleFacedCard from '../components/SingleFacedCard'
import ContactCard from '../components/ContactCard'

const no1 = {
    title: "Das ist eine Überschrift.",
    text: "Häusliche Krankenpflege ist eine Leistung der gesetzlichen Krankenkasse und wird dann durchgeführt, wenn die Versorgung vom Patienten oder dessen Angehörigen nicht selber durchgeführt werden kann.",
    imageSrc: "/../public/assets/leistungen_sample.jpg"
}

const no2 = {
    title: "Das ist eine Überschrift.",
    text: "Häusliche Krankenpflege ist eine Leistung der gesetzlichen Krankenkasse und wird dann durchgeführt, wenn die Versorgung vom Patienten oder dessen Angehörigen nicht selber durchgeführt werden kann.",
    imageSrc: "/../public/assets/leistungen_sample.jpg"
}

const no3 = {
    title: "Das ist eine Überschrift.",
    text: "Häusliche Krankenpflege ist eine Leistung der gesetzlichen Krankenkasse und wird dann durchgeführt, wenn die Versorgung vom Patienten oder dessen Angehörigen nicht selber durchgeführt werden kann.",
    imageSrc: "/../public/assets/leistungen_sample.jpg"
}

const no4 = {
    title: "Das ist eine Überschrift.",
    text: "Häusliche Krankenpflege ist eine Leistung der gesetzlichen Krankenkasse und wird dann durchgeführt, wenn die Versorgung vom Patienten oder dessen Angehörigen nicht selber durchgeführt werden kann.",
    imageSrc: "/../public/assets/leistungen_sample.jpg"
}

export default function leistungen() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main>
                <Wallpaper srcString={"/../public/assets/jobs-wallpaper.jpg"} />
                <div className='max-w-6xl mx-auto flex flex-col lg:flex-row flex-wrap justify-center px-4 lg:px-8 lg:justify-between'>
                    <SingleFacedCard title={no1.title} text={no1.text} imageSrc={no1.imageSrc} />
                    <SingleFacedCard title={no2.title} text={no2.text} imageSrc={no2.imageSrc} />
                    <SingleFacedCard title={no3.title} text={no3.text} imageSrc={no3.imageSrc} />
                    <SingleFacedCard title={no4.title} text={no4.text} imageSrc={no4.imageSrc} />
                    <div className='mx-auto'>
                        <ContactCard />
                    </div>
                </div>
            </main>
            <Footer />
        </>
    )
}
